# Generated by Django 4.2 on 2023-05-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='coursehsc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
