# Generated by Django 4.2.1 on 2023-05-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeeleave_leavedaterange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeLeave',
        ),
    ]
