# Generated by Django 4.2.5 on 2023-10-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employeeleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='leavetype',
            field=models.CharField(default='casual', max_length=100),
        ),
    ]
