# Generated by Django 4.2.5 on 2023-10-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employeetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='sub_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
